import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, ChevronRight, CircleDot, FlaskConical, Play, RotateCcw, Sparkles } from 'lucide-react';
import './styles.css';

const TOTAL = 6;

function Typewriter({ text, active, speed = 26 }) {
  const [visible, setVisible] = useState('');
  useEffect(() => {
    if (!active) return;
    setVisible('');
    let index = 0;
    const timer = window.setInterval(() => {
      index += 1;
      setVisible(text.slice(0, index));
      if (index >= text.length) window.clearInterval(timer);
    }, speed);
    return () => window.clearInterval(timer);
  }, [text, active, speed]);
  return <>{visible}<span className="caret" /></>;
}

function SectionFrame({ children, index, onNext, onPrev, nextLabel = '下一步', restart }) {
  return <main className="screen">
    <div className="topline"><span>OPENAI4S / SCIENTIFIC WORKFLOWS</span><span>DEMO 2026</span></div>
    {children}
    <div className="progress"><span>{String(index + 1).padStart(2, '0')} / {String(TOTAL).padStart(2, '0')}</span><div className="progress-track"><i style={{ width: `${((index + 1) / TOTAL) * 100}%` }} /></div></div>
    <div className="navigation">
      {index > 0 ? <button className="icon-button" onClick={onPrev} aria-label="上一页"><ArrowLeft size={19} /></button> : <span />}
      {restart ? <button className="next-button" onClick={restart}>重新播放 <RotateCcw size={17} /></button> : <button className="next-button" onClick={onNext}>{nextLabel} {index === TOTAL - 1 ? <RotateCcw size={17} /> : <ArrowRight size={18} />}</button>}
    </div>
  </main>;
}

function Molecule({ small = false }) {
  return <svg className={small ? 'molecule small' : 'molecule'} viewBox="0 0 340 210" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="2"><path d="M69 120 119 91l51 29v56l-50 29-51-29zM170 120l49-29 51 29v56l-51 29-49-29zM219 91l29-50 58 1 28 50-29 49-57 1z"/><path d="m119 91 1-58m100 58 29 50m-79-21 49 29" strokeOpacity=".45" /></g><g fill="currentColor"><circle cx="69" cy="120" r="8"/><circle cx="120" cy="91" r="8"/><circle cx="170" cy="120" r="8"/><circle cx="219" cy="91" r="8"/><circle cx="277" cy="41" r="8"/><circle cx="334" cy="92" r="8"/><circle cx="305" cy="141" r="8"/><circle cx="220" cy="205" r="8"/><circle cx="120" cy="205" r="8"/></g></svg>;
}

function DNA() { return <svg className="dna" viewBox="0 0 190 320" aria-hidden="true"><path d="M30 0c130 38 0 72 130 110S30 183 160 220 30 282 160 320M160 0C30 38 160 72 30 110s130 73 0 110 130 62 0 100" fill="none" stroke="currentColor" strokeWidth="5"/><g stroke="currentColor" strokeWidth="2" opacity=".65"><path d="M48 30h94M56 73h78M68 145h56M60 190h69M58 262h74M76 300h39"/></g></svg>; }

function Cover({ next }) { return <SectionFrame index={0} onNext={next} nextLabel="Explore"><div className="cover-art"><DNA /><Molecule /><div className="spectrum-lines" /></div><div className="cover-content"><div className="eyebrow"><Sparkles size={15} /> SCIENTIFIC AI, ORCHESTRATED</div><h1>OpenAI4S</h1><p>一个面向科学问题求解的<br /><strong>AI harness</strong></p><div className="domains"><span>有机化学</span><span>生命科学</span><span>新材料</span></div></div></SectionFrame>; }

const chemistryTasks = [{ n: '01', name: '类药性优化', detail: 'ADMET / molecular design' }, { n: '02', name: '合成路径分析', detail: 'retrosynthesis planning' }, { n: '03', name: '混合物成分分析', detail: 'Raman spectra / NNLS', active: true }];
const lifeTasks = [{ n: '01', name: '蛋白-分子靶点', detail: 'structural reasoning / docking' }, { n: '02', name: '蛋白定向突变', detail: 'ESM scoring / structure ranking', active: true }];
function Overview({ index, title, label, tasks, next, prev }) { return <SectionFrame index={index} onNext={next} onPrev={prev}><div className="overview"><div className="overview-copy"><div className="eyebrow"><CircleDot size={15} /> DOMAIN / {label}</div><h2>{title}</h2><p>{index === 1 ? '让模型阅读科学数据，以可追溯的工具链完成从谱图到结论的分析。' : '将语言模型、序列模型与结构预测组合为可检查的设计闭环。'}</p><div className="scope-line">03 READY-TO-RUN SKILLS</div></div><div className="task-stack">{tasks.map((task, i) => <motion.div key={task.name} className={`task-card ${task.active ? 'active' : ''}`} initial={{ opacity: 0, x: 44 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.18 + i * .12 }}><span className="task-number">{task.n}</span><div><h3>{task.name}</h3><p>{task.detail}</p></div><ChevronRight size={20} /></motion.div>)}</div></div></SectionFrame>; }

function Spectrum() { const pts = '0,174 12,172 24,176 36,169 48,165 60,173 72,145 84,165 96,155 108,162 120,120 132,159 144,146 156,156 168,133 180,157 192,126 204,149 216,99 228,144 240,137 252,147 264,78 276,140 288,121 300,145 312,133 324,153 336,90 348,149 360,132 372,155 384,141 396,151 408,118 420,145 432,132 444,143 456,95 468,138 480,123 492,148 504,140 516,156 528,151 540,159'; return <svg className="spectrum" viewBox="0 0 560 220" preserveAspectRatio="none"><g className="grid"><path d="M0 40H560M0 85H560M0 130H560M0 175H560M60 0V190M180 0V190M300 0V190M420 0V190M540 0V190"/></g><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 190H560" className="axis"/><text x="0" y="215">150</text><text x="510" y="215">1400 cm⁻¹</text></svg>; }

const mineralCode = ["spectrum = load_spectrum_csv('case1/spectrum.csv')", 'clean = preprocess_once(spectrum, despike=True, baseline="asls")', 'matches = iterative_residual_match(clean, library="RRUFF")', 'result = nnls_unmix(clean, matches)', 'report = summarize(result, confidence="high")'];
const proteinCode = ["library = enumerate_mutants(wt, positions=active_sites, max_order=1)", 'esm_scores = score_sequence_effect(library, model="fair-esm2")', 'folds = predict_structures(top(esm_scores, 32), model="esmfold2")', 'ranked = merge_and_rank(esm_scores, folds, weights=DEFAULT)', 'accepted = apply_thresholds(ranked, plddt=75, composite=0.72)'];
function CodePanel({ kind }) { const code = kind === 'mineral' ? mineralCode : proteinCode; const logs = kind === 'mineral' ? ['Loaded 626 spectral points', '28 peaks retained after preprocessing', 'Residual loop complete: 3 components', 'NNLS fit correlation: 0.983'] : ['Round 1 library: 228 variants', 'ESM sequence scores merged', 'Structure metrics received: 32 candidates', '3 variants passed acceptance gates']; return <div className="agent-panel"><div className="agent-head"><div><span className="live-dot" /> AGENT WORKSPACE</div><span>{kind === 'mineral' ? 'mineral_spectra_analysis' : 'protein-mutation-enhancement'}</span></div><div className="agent-grid"><section><small>TASK DESCRIPTION</small><p>{kind === 'mineral' ? 'Blind identification and NNLS unmixing of an unknown Raman mineral mixture.' : 'Build and score a directed protein-mutation library, then rank valid candidates.'}</p></section><section className="code"><small>GENERATED CODE</small>{code.map((line, i) => <div key={line} className="code-line"><b>{String(i + 1).padStart(2, '0')}</b><span>{line}</span></div>)}</section><section className="logs"><small>EXECUTION LOG</small>{logs.map((line, i) => <div key={line} className="log-line" style={{ animationDelay: `${i * .5}s` }}><Check size={13}/>{line}</div>)}</section></div></div>; }

function MineralResult() { const data = [['Diopside', '45.7%', '180 · 232 · 324 · 1012 cm⁻¹', 'aqua'], ['Bertrandite', '29.6%', '182 · 202 · 710 · 926 cm⁻¹', 'cobalt'], ['Clinoptilolite-Ca', '24.7%', '220 · 260 · 482 · 614 cm⁻¹', 'violet']]; return <div className="results"><div className="result-head"><div><span className="eyebrow"><Check size={14}/> BLIND ANALYSIS COMPLETE</span><h3>3 mineral phases identified</h3></div><div className="confidence">HIGH CONFIDENCE<br/><strong>r = 0.983</strong></div></div>{data.map(([name, fraction, peaks, color]) => <div className="mineral-row" key={name}><span className={`color-dot ${color}`} /><div className="mineral-name"><strong>{name}</strong><small>{peaks}</small></div><div className="bar"><i className={color} style={{ width: fraction }} /></div><b>{fraction}</b></div>)}<p className="result-note">28 clean peaks · 0 residual peaks · NNLS unmixing · RRUFF reference library</p></div>; }

function ProteinVisual() { return <svg className="protein-visual" viewBox="0 0 500 360" aria-hidden="true"><defs><filter id="soft"><feGaussianBlur stdDeviation="3"/></filter></defs><g fill="none" strokeLinecap="round"><path d="M57 236C51 129 156 49 237 101c70 44 9 109 84 139 61 25 129-33 130-115" stroke="#3e78f0" strokeWidth="16"/><path d="M33 193c86 36 102-84 173-68 67 15 70 102 145 79 59-18 46-83 117-74" stroke="#28baae" strokeWidth="17"/><path d="M82 282c52-26 77-82 134-53 49 25 93 80 166 26" stroke="#774ee8" strokeWidth="14"/><path d="M125 64c25 70 88 41 113 83 21 36-29 69 29 99" stroke="#f0a83a" strokeWidth="11"/></g><g fill="#f7faf9" stroke="#172c41" strokeWidth="2"><circle cx="259" cy="184" r="41"/><circle cx="259" cy="184" r="22"/></g><text x="230" y="190" fill="#172c41" fontSize="12">ACTIVE</text><text x="230" y="204" fill="#172c41" fontSize="12">SITE</text></svg>; }

function ProteinResult() { const rows = [['T3L+Y5V', '0.89', '88.4', '0.72'], ['A12V', '0.81', '86.0', '0.78'], ['G47D+S50T', '0.76', '82.7', '0.74']]; return <div className="protein-results"><div className="result-head"><div><span className="eyebrow"><Check size={14}/> DESIGN ROUND 01</span><h3>Prioritized variants</h3></div><div className="confidence">ACCEPTANCE<br/><strong>3 / 228</strong></div></div><div className="protein-table"><div className="table-head"><span>VARIANT</span><span>COMPOSITE</span><span>pLDDT</span><span>PROPERTY</span></div>{rows.map(([id, score, plddt, property], i) => <div className="protein-row" key={id}><span className="rank">0{i + 1}</span><strong>{id}</strong><span>{score}</span><span>{plddt}</span><span>{property}</span></div>)}</div><p className="result-note">Weighted ranking: ESM sequence effect · structural confidence · RMSD · local property heuristic</p></div>; }

function Demo({ kind, index, next, prev }) { const [phase, setPhase] = useState(0); const mineral = kind === 'mineral'; useEffect(() => { setPhase(0); const timings = [1200, 3400, 6900]; const timers = timings.map((time, i) => window.setTimeout(() => setPhase(i + 1), time)); return () => timers.forEach(window.clearTimeout); }, [kind]); const prompt = mineral ? '请针对提供的未知混合物拉曼光谱开展一次盲测成分鉴定与解混分析' : '针对目标蛋白的关键活性位点，构建突变库并筛选具有更优综合得分的候选变体'; return <SectionFrame index={index} onNext={next} onPrev={prev} nextLabel={mineral ? '生命科学' : '完成'}><div className="demo-title"><span className="eyebrow"><FlaskConical size={15}/> LIVE SCIENTIFIC WORKFLOW</span><h2>{mineral ? '混合物成分分析' : '蛋白定向突变'}</h2></div><div className="demo-stage"><AnimatePresence mode="wait">{phase < 1 && <motion.div key="source" className={`source-visual ${mineral ? 'spectral-card' : 'protein-card'}`} initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .45, y: 84 }} transition={{ duration: .65 }}><div className="visual-label">{mineral ? 'UNKNOWN RAMAN SPECTRUM / CASE 1' : 'TARGET PROTEIN / ACTIVE-SITE REGION'}</div>{mineral ? <Spectrum /> : <ProteinVisual />}</motion.div>}</AnimatePresence><AnimatePresence>{phase >= 1 && phase < 3 && <motion.div className="prompt-box" initial={{ opacity: 0, y: 40, scale: .88 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, x: -90 }} transition={{ duration: .5 }}><div className="prompt-attachment">{mineral ? <Spectrum /> : <ProteinVisual />}</div><div className="prompt-text"><small>OPENAI4S TASK</small><p><Typewriter active={phase >= 1} text={prompt} /></p></div><button aria-label="运行任务"><Play size={17} fill="currentColor" /></button></motion.div>}</AnimatePresence><AnimatePresence>{phase === 2 && <motion.div className="agent-fade" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><CodePanel kind={kind} /></motion.div>}{phase === 3 && <motion.div className="result-fade" initial={{ opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}>{mineral ? <MineralResult /> : <ProteinResult />}</motion.div>}</AnimatePresence></div><button className="replay" onClick={() => setPhase(0)}><RotateCcw size={14}/> replay workflow</button></SectionFrame>; }

function End({ prev, restart }) { return <SectionFrame index={5} onPrev={prev} restart={restart}><div className="end"><div className="end-mark"><Molecule /></div><div className="eyebrow"><Sparkles size={15}/> ONE HARNESS, MANY SCIENTIFIC WORKFLOWS</div><h1>OpenAI4S</h1><p>将自然语言、科学实体、推理与工具执行连接成统一的<br />AI 驱动科学问题求解系统。</p><div className="capabilities"><span>natural language prompting</span><span>scientific entity grounding</span><span>agentic reasoning and coding</span><span>automated scientific analysis</span></div><a href="https://github.com/OpenAI4S/openai4s" target="_blank" rel="noreferrer">github.com/OpenAI4S/openai4s <ArrowRight size={16}/></a></div></SectionFrame>; }

function App() { const [page, setPage] = useState(0); const next = () => setPage(p => Math.min(TOTAL - 1, p + 1)); const prev = () => setPage(p => Math.max(0, p - 1)); const screens = useMemo(() => [<Cover next={next}/>, <Overview index={1} title="有机化学" label="CHEMISTRY" tasks={chemistryTasks} next={next} prev={prev}/>, <Demo kind="mineral" index={2} next={next} prev={prev}/>, <Overview index={3} title="生命科学" label="LIFE SCIENCE" tasks={lifeTasks} next={next} prev={prev}/>, <Demo kind="protein" index={4} next={next} prev={prev}/>, <End prev={prev} restart={() => setPage(0)}/>], []); useEffect(() => { const key = e => { if (e.key === 'ArrowRight' || e.key === ' ') next(); if (e.key === 'ArrowLeft') prev(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }); return <div className="app"><AnimatePresence mode="wait">{React.cloneElement(screens[page], { key: page })}</AnimatePresence></div>; }

createRoot(document.getElementById('root')).render(<App />);
